### PR TITLE
weave kilim benchmark and use a valid pause reason

### PR DESCRIPTION
**Pull request by nqzero**
i haven't updated the readme to include the results to avoid future conflicts but a shortened run gives:

```
Benchmark                                  Mode  Cnt     Score   Error  Units
AkkaActorRingBenchmark.ringBenchmark       avgt    2   623.091          ms/op
JavaThreadRingBenchmark.ringBenchmark      avgt    2  6139.337          ms/op
KilimFiberRingBenchmark.ringBenchmark      avgt    2   430.492          ms/op
QuasarActorRingBenchmark.ringBenchmark     avgt    2  2655.926          ms/op
QuasarChannelRingBenchmark.ringBenchmark   avgt    2  1544.488          ms/op
QuasarDataflowRingBenchmark.ringBenchmark  avgt    2  2033.488          ms/op
QuasarFiberRingBenchmark.ringBenchmark     avgt    2   704.593          ms/op
```

### CODE REVIEW

**Comment by nqzero** [comment]
i guess that when i pushed the rest of my commits to github, the pull request automatically pulled in the changes to the readme (or maybe i mis-clicked on something). can't find an obvious way to undo it. please ignore the 4th commit (5a8ff80)

updated numbers from the readme:
```
Benchmark                                     Mode  Cnt     Score      Error  Units
AkkaActorRingBenchmark.ringBenchmark          avgt    4   614.755 ±  151.874  ms/op
JavaThreadRingBenchmark.ringBenchmark         avgt    4  6126.367 ±  304.880  ms/op
KilimActorRingBenchmark.ringBenchmark         avgt    4   611.655 ±  128.317  ms/op
KilimContinuationRingBenchmark.ringBenchmark  avgt    4    45.544 ±   11.303  ms/op
KilimFiberRingBenchmark.ringBenchmark         avgt    4   441.433 ±   61.134  ms/op
QuasarActorRingBenchmark.ringBenchmark        avgt    4  2627.271 ± 2114.870  ms/op
QuasarChannelRingBenchmark.ringBenchmark      avgt    4  1589.085 ±  819.561  ms/op
QuasarDataflowRingBenchmark.ringBenchmark     avgt    4  1866.151 ±  302.077  ms/op
QuasarFiberRingBenchmark.ringBenchmark        avgt    4   666.120 ±  148.967  ms/op
```

**Comment by vy** [comment]
Fantastic additions @nqzero! I will merge them as soon as I wrap my head around it, which I do expect to happen before next Monday. In the meantime, would you mind helping me to figure out a couple of details:
- What is the effect of `Scheduler.defaultNumberThreads = 1`? If this would confine Kilim to a single thread, Kilim will not be able to employ all cores, but stay free from context switches. Don't you think this is a little bit unfair given the rest of the approaches try to employ all the cores?
- In `KilimFiberRingBenchmark`, why do we need to check whether all fibers are started or not?
- `Thread.sleep(1)` smells funky. Are you sure it will still be fine on some weird platform? Would you mind sharing the rationale behind that?
- The `scheduler` in `KilimContinuationRingBenchmark` also suffers from processing all the tasks on a single thread. Though this is still an interesting test case.

I will add Project Loom fibers sometime this month. I think your contributions will definitely heat up the competition. Thanks for the help.

**Comment by nqzero** [comment]
thanks @vy 

* i wanted a scheduler that was appropriate for the payload. in real life i'd use a dedicated scheduler (with `setScheduler()`) for this, but since there are no other tasks, i just set the default. yes, it limits it to a single thread which is exactly what i wanted for this workload

* if a task hasn't `paused()` before it gets `resumed()` then the program would hang (i think) or behave erratically. i think `resume()` is a low level interface (i've never used it directly before). we could add a cleaner metaphor for "fully starting" a task, but normally you'd just use continuations so it wouldn't be used much. `unpark` for quasar is low level too afaik, and it's possible that a similar issue is what's causing it to hang for me with small ring sizes

* `Thread.sleep(1)` is just plain java and should run everywhere but it could be replaced with a spin-lock (which would be fractionally faster but i was trying to conserve cpu - a general theme with kilim)

* my continuation variant might be a good starting point for loom (the apis are similar)

**Comment by nqzero** [comment]
i updated master with a few changes to `KilimFiber`. the old code is available in tag pull.4

this reorders the loop to avoid the check after starting the fibers

**Comment by nqzero** [comment]
> given the rest of the approaches try to employ all the cores

at least for quasar, i don't think this is quite true. quasar uses a fork join pool to execute fibers which generally forks tasks onto the current thread. other threads can steal them, but with low-cpu tasks such as these i'd expect very little thread stealing (the javadocs suggest that for less than 100 computation tasks)

here's a branch with the kilim benchmarks running on a minimal fork/join scheduler
https://github.com/nqzero/fiber-test/tree/fork

i also added KilimThrashRingBenchmark

**Comment by nqzero** [comment]
decided other people might be interested in the fork join scheduler so pulled that into kilim itself (2.0.0-29) and updated the benchmarks to use both schedulers

**Comment by vy** [comment]
Hey @nqzero! I wanted to let you know that I did not forget about this issue, but (during off work hours, that is, evenings+nights) I am pretty much swamped by [log4j2-logstash-layout issue #17](https://github.com/vy/log4j2-logstash-layout/issues/17) at the moment. I am doing my best to wrap it up and return back to this pursuit.

**Comment by vy** [comment]
Thanks so much @nqzero! I have merged your changes. What I will further do is as follows:

1. Add `threadCount` parameter to tests to control the number of threads used by the frameworks.
2. Make `benchmark.sh` to align `threadCount` with `taskset`.
3. Add multi-JDK support. (Quasar does have support up to Java 8, Loom requires Java 11, etc.)
4. Add Loom fibers and continuations.

**Pull request closed without merging**
